"""Proof-obligation generator (competition v1). TRUSTED.

Turns (reference program, competitor chain of programs, step kinds, candidate
digest) into the Lean module `Contest.Obligation`. The competitor never writes
any part of this module: programs enter it only as data, rendered by
`lean_expr` from IR that `verifiedir.validate` has already accepted (every
name matches a strict identifier regex, every number is a bounded integer),
so no competitor-controlled text can reach the Lean parser as syntax.

The generated module has one namespace per workload `w` (context `ctx`
fixed by the competition from the reference program) containing:

  * for each library-rule step k:  theorem step_k : Equiv ctx P_k P_{k+1}
      proved HERE by the kernel evaluating the rule checker
      (`step_equiv ctx P_k P_{k+1} s (by decide) rfl`);
  * for each lemma step k:         def goal_k : Prop :=
                                     Stamped "<stamp>/<w>/step/k" (Equiv ctx P_k P_{k+1})
      which the competitor's exported proof must inhabit;
  * def Claim : Prop := Equiv ctx P_0 P_n

and, at the top level, the single root statement

  * def RootGoal : Prop := Stamped "<stamp>" (w1.Claim ∧ w2.Claim ∧ ...)
  * theorem root_of_steps (h : goal)... : RootGoal
      (composition by Equiv.trans; proved here).
"""

from __future__ import annotations

import hashlib
import re
import sys

sys.path.insert(0, __import__("os").path.join(__import__("os").path.dirname(__file__), "..", "schema"))
from verifiedir import ADT_NAME_RE, NAME_RE, PRIMS  # noqa: E402

sys.setrecursionlimit(20000)

STAMP_RE = re.compile(r"^[A-Za-z0-9:/._-]{1,512}$")
RULES = {"inline": ".inline", "caseCtr": ".caseCtr", "natLit": ".natLit"}


def lean_ty(t) -> str:
    if t == "u32":
        return ".u32"
    if t == "nat":
        return ".nat"
    return f"(.adt {int(t[1])})"


def lean_str(s: str, regex=NAME_RE) -> str:
    if not regex.match(s):
        raise ValueError(f"refusing to render non-identifier string {s!r}")
    return '"' + s + '"'


def lean_list(xs) -> str:
    return "[" + ", ".join(xs) + "]"


def lean_expr(e) -> str:
    tag = e[0]
    if tag == "var":
        return f"(.var {int(e[1])})"
    if tag == "u32":
        return f"(.u32 {int(e[1])})"
    if tag == "nat":
        return f"(.nat {int(e[1])})"
    if tag == "prim":
        if e[1] not in PRIMS:
            raise ValueError("unknown primitive")
        return f"(.prim .{e[1]} {lean_list(lean_expr(a) for a in e[2])})"
    if tag == "ctr":
        return f"(.ctr {int(e[1])} {int(e[2])} {lean_list(lean_expr(a) for a in e[3])})"
    if tag == "call":
        return f"(.call {int(e[1])} {lean_list(lean_expr(a) for a in e[2])})"
    if tag == "let":
        return f"(.let_ {lean_expr(e[1])} {lean_expr(e[2])})"
    if tag == "par":
        return f"(.par {lean_expr(e[1])} {lean_expr(e[2])} {lean_expr(e[3])})"
    if tag == "mat":
        arms = lean_list(f"({int(k)}, {lean_expr(b)})" for k, b in e[3])
        return f"(.mat {int(e[1])} {lean_expr(e[2])} {arms})"
    if tag == "natcase":
        return f"(.natCase {lean_expr(e[1])} {lean_expr(e[2])} {lean_expr(e[3])})"
    raise ValueError(f"unknown expression tag {tag!r}")


def lean_adt(a) -> str:
    ctors = lean_list(f"⟨{lean_str(c['name'])}, {lean_list(lean_ty(t) for t in c['fields'])}⟩"
                      for c in a["ctors"])
    return f"⟨{lean_str(a['name'], ADT_NAME_RE)}, {ctors}⟩"


def lean_rule(step) -> str:
    r = step["rule"]
    if r["name"] == "fold":
        return f"(.fold {int(r['bool_adt'])})"
    return RULES[r["name"]]


def lean_ns(workload: str) -> str:
    ns = workload.replace("-", "_")
    if not NAME_RE.match(ns) or "." in ns:
        raise ValueError(f"bad workload name {workload!r}")
    return ns


def generate(workloads, stamp: str):
    """workloads = [{"name", "ctx", "programs": [P_0..P_n], "steps": [n steps]}, ...]
    ctx = {"adts": [...], "entry": str, "params": [Ty], "ret": Ty} (from the reference).

    Returns (lean_source, lemma_goals) where lemma_goals lists the fully
    qualified goal constants, in the order `root_of_steps` expects proofs."""
    if not STAMP_RE.match(stamp):
        raise ValueError("bad stamp")
    out = ["-- GENERATED BY trusted/proof-generator/obligation.py. DO NOT EDIT.",
           "import BendVerify", "", "namespace Contest.Obligation", "open BendVerify", ""]
    adt_names: dict[str, str] = {}
    body_names: dict[str, str] = {}

    def adt_ref(a) -> str:
        txt = lean_adt(a)
        h = hashlib.sha256(txt.encode()).hexdigest()[:16]
        if txt not in adt_names:
            adt_names[txt] = f"adt_{h}"
            out.append(f"def adt_{h} : Adt := {txt}")
        return adt_names[txt]

    def body_ref(b) -> str:
        txt = lean_expr(b)
        h = hashlib.sha256(txt.encode()).hexdigest()[:16]
        if txt not in body_names:
            body_names[txt] = f"body_{h}"
            out.append(f"def body_{h} : Expr := {txt}")
        return body_names[txt]

    lemma_goals: list[str] = []
    hyp_binders: list[str] = []
    claims: list[str] = []
    proofs: list[str] = []   # per workload: the composed Equiv term, in terms of hypotheses
    for w in workloads:
        ns = lean_ns(w["name"])
        ctx, programs, steps = w["ctx"], w["programs"], w["steps"]
        if len(programs) != len(steps) + 1:
            raise ValueError("programs/steps mismatch")
        ctx_adts = lean_list(adt_ref(a) for a in ctx["adts"])
        defs = []
        for k, p in enumerate(programs):
            adts = lean_list(adt_ref(a) for a in p["adts"])
            fns = lean_list(
                f"⟨{lean_str(f['name'])}, {lean_list(lean_ty(t) for t in f['params'])}, "
                f"{lean_ty(f['ret'])}, {body_ref(f['body'])}⟩" for f in p["fns"])
            defs.append(f"def P_{k} : Prog := ⟨{adts}, {fns}⟩")
        out.append(f"namespace {ns}")
        out.append(f"def ctx : Ctx := ⟨{ctx_adts}, {lean_str(ctx['entry'])}, "
                   f"{lean_list(lean_ty(t) for t in ctx['params'])}, {lean_ty(ctx['ret'])}⟩")
        out.extend(defs)
        parts = []
        for k, s in enumerate(steps):
            if s["kind"] == "rule":
                path = lean_list(str(int(i)) for i in s["path"])
                out.append(f"theorem wf_{k} : wfEntryB ctx P_{k} = true := by decide")
                out.append(f"theorem step_{k} : Equiv ctx P_{k} P_{k + 1} :=")
                out.append(f"  step_equiv ctx P_{k} P_{k + 1} ⟨{int(s['fn'])}, {path}, {lean_rule(s)}⟩ wf_{k} rfl")
                parts.append(f"{ns}.step_{k}")
            elif s["kind"] == "lemma":
                out.append(f"def goal_{k} : Prop := Stamped \"{stamp}/{w['name']}/step/{k}\" "
                           f"(Equiv ctx P_{k} P_{k + 1})")
                lemma_goals.append(f"Contest.Obligation.{ns}.goal_{k}")
                hyp_binders.append(f"(h_{ns}_{k} : {ns}.goal_{k})")
                parts.append(f"h_{ns}_{k}.claim")
            else:
                raise ValueError("unknown step kind")
        n = len(steps)
        out.append(f"/-- The workload's claim: the candidate program is equivalent to the reference. -/")
        out.append(f"def Claim : Prop := Equiv ctx P_0 P_{n}")
        if n == 0:
            out.append(f"theorem wf_final : wfEntryB ctx P_0 = true := by decide")
            proofs.append(f"(Equiv.refl (wfEntryB_sound {ns}.wf_final))")
        else:
            chain = parts[-1]
            for p in reversed(parts[:-1]):
                chain = f"(Equiv.trans {p} {chain})"
            proofs.append(chain)
        out.append(f"end {ns}")
        out.append("")
        claims.append(f"{ns}.Claim")
    out.append("/-- The certified root statement: CandidateValid(competition id, candidate digest). -/")
    out.append(f"def RootGoal : Prop := Stamped \"{stamp}\" ({' ∧ '.join(claims)})")
    out.append(f"theorem root_of_steps {' '.join(hyp_binders)} : RootGoal := by")
    out.append("  refine ⟨Stamp.mk _, ?_⟩")
    tup = proofs[-1]
    for p in reversed(proofs[:-1]):
        tup = f"⟨{p}, {tup}⟩"
    out.append(f"  exact {tup}")
    out.append("")
    out.append("end Contest.Obligation")
    return "\n".join(out) + "\n", lemma_goals
